id: PE888F9B3
initial_creation_type: ocr
source_metadata:
  volumes:
    d94b7efc3725498faf5ceab31ab1cecb:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: འཕགས་པ་རྗེ་བཙུན་འཇམ་དཔལ་གྱི་དོན་དམ་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
